# Avaliação do RAG — CLT

## Objetivo

Avaliar a qualidade das respostas geradas pelo pipeline RAG (Retrieval-Augmented Generation) sobre a CLT brasileira.

## Metodologia

Utilizamos duas abordagens complementares:

1. **Avaliação automática por palavra-chave (Keyword Accuracy):** verifica se a resposta gerada contém termos-chave esperados (ex.: número do artigo, valor numérico). É rápida e objetiva, mas não captura qualidade semântica.
2. **Análise qualitativa:** comparação manual entre a resposta esperada e a gerada, observando precisão, completude, citação de artigos e clareza.

## Dataset de Avaliação

O arquivo `tests/questions_benchmark.json` contém **10 perguntas** cobrindo os principais temas trabalhistas:
férias, aviso prévio, jornada de trabalho, hora extra, FGTS, licença maternidade,
intervalo intrajornada, rescisão, salário mínimo e trabalho noturno.

---

## 1. Configuração do Ambiente

In [2]:
import json
import sys
from pathlib import Path

import pandas as pd

# Adiciona a raiz do projeto ao sys.path para importar src.*
project_root = Path("..").resolve()
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from src.retrieval.chain import get_answer

print(f"Raiz do projeto: {project_root}")
print("Módulos carregados com sucesso.")

Raiz do projeto: C:\Users\teodo\OneDrive\Documentos\Faculdade\6 Semestre Data Science\NLP\clt-rag-chatbot
Módulos carregados com sucesso.

## 2. Carregamento do Benchmark

In [3]:
benchmark_path = project_root / "tests" / "questions_benchmark.json"

with open(benchmark_path, encoding="utf-8") as f:
    benchmark = json.load(f)

print(f"{len(benchmark)} perguntas carregadas.")
print(f"Temas: {', '.join(item['topic'] for item in benchmark)}")

10 perguntas carregadas.
Temas: férias, aviso prévio, jornada de trabalho, hora extra, FGTS, licença maternidade, intervalo intrajornada, rescisão, salário mínimo, trabalho noturno

## 3. Execução dos Testes

Cada pergunta é avaliada de forma isolada (`chat_history=[]`), simulando uma consulta nova ao sistema.

In [4]:
results = []

for item in benchmark:
    # Avaliação isolada: sem histórico de conversa
    generated = get_answer(item["question"], chat_history=[])

    keyword_hit = any(
        kw.lower() in generated.lower() for kw in item["expected_keywords"]
    )

    results.append({
        "id": item["id"],
        "topic": item["topic"],
        "question": item["question"],
        "expected_answer": item["expected_answer"],
        "expected_keywords": item["expected_keywords"],
        "generated_answer": generated,
        "keyword_hit": keyword_hit,
    })

    status = "✅" if keyword_hit else "❌"
    print(f"{status} [{item['topic']:25s}] {item['question'][:60]}...")

✅ [férias                   ] Quantos dias de férias o trabalhador tem direito após 12 mes...
✅ [aviso prévio             ] Qual é o prazo mínimo do aviso prévio na demissão sem justa ...
✅ [jornada de trabalho      ] Qual é a jornada máxima de trabalho diária e semanal previst...
✅ [hora extra               ] Qual o acréscimo mínimo que deve ser pago ao trabalhador por...
✅ [FGTS                     ] Qual é o percentual do FGTS que o empregador deve depositar ...
✅ [licença maternidade      ] Qual é a duração da licença-maternidade prevista na CLT?...
✅ [intervalo intrajornada   ] Qual é o intervalo mínimo para refeição e descanso em jornad...
✅ [rescisão                 ] Quais verbas rescisórias o trabalhador recebe ao ser demitid...
✅ [salário mínimo           ] Como a CLT define o salário mínimo e quais necessidades ele ...
✅ [trabalho noturno         ] Qual é o adicional noturno previsto na CLT e como é contada ...

## 4. Métricas de Avaliação Automática

In [5]:
total = len(results)
hits = sum(r["keyword_hit"] for r in results)
accuracy = hits / total

print(f"Total de perguntas : {total}")
print(f"Acertos (keyword)  : {hits}")
print(f"Erros              : {total - hits}")
print(f"Keyword Accuracy   : {accuracy:.0%}")

Total de perguntas : 10
Acertos (keyword)  : 10
Erros              : 0
Keyword Accuracy   : 100%

In [6]:
df = pd.DataFrame(results)[[
    "id", "topic", "question", "keyword_hit", "expected_keywords"
]]
df["keyword_hit"] = df["keyword_hit"].map({True: "✅", False: "❌"})
df["expected_keywords"] = df["expected_keywords"].apply(", ".join)
df.set_index("id", inplace=True)

pd.set_option("display.max_colwidth", 80)
df

,topic,question,keyword_hit,expected_keywords
id,,,,
1,férias,Quantos dias de férias o trabalhador tem direito após 12 meses de trabalho?,✅,"30 dias, Art. 130"
2,aviso prévio,Qual é o prazo mínimo do aviso prévio na demissão sem justa causa?,✅,"30 dias, Art. 487"
3,jornada de trabalho,Qual é a jornada máxima de trabalho diária e semanal prevista na CLT?,✅,"8 horas, 44 horas, Art. 58"
4,hora extra,Qual o acréscimo mínimo que deve ser pago ao trabalhador por hora extra?,✅,"50%, Art. 59"
5,FGTS,Qual é o percentual do FGTS que o empregador deve depositar mensalmente?,✅,"8%, FGTS"
6,licença maternidade,Qual é a duração da licença-maternidade prevista na CLT?,✅,"120 dias, Art. 392"
7,intervalo intrajornada,Qual é o intervalo mínimo para refeição e descanso em jornadas acima de 6 ho...,✅,"1 hora, Art. 71"
8,rescisão,Quais verbas rescisórias o trabalhador recebe ao ser demitido sem justa causa?,✅,"aviso prévio, férias, FGTS, 40%"
9,salário mínimo,Como a CLT define o salário mínimo e quais necessidades ele deve cobrir?,✅,"Art. 76, salário mínimo"
10,trabalho noturno,Qual é o adicional noturno previsto na CLT e como é contada a hora noturna?,✅,"20%, Art. 73, 52 minutos"

## 5. Comparação Resposta Esperada × Resposta Gerada

In [7]:
for r in results:
    status = "✅" if r["keyword_hit"] else "❌"
    print(f"{'='*70}")
    print(f"{status} Pergunta #{r['id']} — {r['topic'].upper()}")
    print(f"\nP: {r['question']}")
    print(f"\n[ESPERADO]\n{r['expected_answer']}")
    print(f"\n[GERADO]\n{r['generated_answer']}")
    print()

======================================================================
✅ Pergunta #1 — FÉRIAS

P: Quantos dias de férias o trabalhador tem direito após 12 meses de trabalho?

[ESPERADO]
O trabalhador tem direito a 30 dias corridos de férias após cada período aquisitivo de 12 meses, conforme o Art. 130 da CLT. As férias podem ser divididas em até três períodos, sendo que um deles não pode ser inferior a 14 dias corridos.

[GERADO]
Conforme o Art. 130 da CLT, após cada período de 12 (doze) meses de vigência do contrato de trabalho, o empregado terá direito a férias na seguinte proporção, que varia de acordo com o número de faltas ao serviço:

*   **30 (trinta) dias corridos**, se não houver faltado ao serviço mais de 5 (cinco) vezes (Art. 130, I).
*   **24 (vinte e quatro) dias corridos**, se houver tido de 6 (seis) a 14 (quatorze) faltas (Art. 130, II).
*   **18 (dezoito) dias corridos**, se houver tido de 15 (quinze) a 23 (vinte e três) faltas (Art. 130, III).
*   **12 (doze) dias corridos**, se houver tido de 24 (vinte e quatro) a 32 (trinta e duas) faltas (Art. 130, IV).

É importante notar que as faltas mencionadas são aquelas que não são justificadas ou abonadas pela lei. O Art. 130, § 1º, estabelece que é vedado descontar, do período de férias, as faltas do empregado ao serviço.

======================================================================
✅ Pergunta #2 — AVISO PRÉVIO

P: Qual é o prazo mínimo do aviso prévio na demissão sem justa causa?

[ESPERADO]
O aviso prévio mínimo é de 30 dias, conforme o Art. 487 da CLT. Além disso, a legislação prevê o acréscimo de 3 dias por ano de serviço prestado ao mesmo empregador, até o limite máximo de 90 dias.

[GERADO]
Conforme os trechos da CLT fornecidos, o prazo mínimo do aviso prévio na demissão sem justa causa é de **30 (trinta) dias**.

Essa informação é encontrada em diferentes artigos:

*   **Art. 23, § 1º**: Estabelece que o aviso prévio será concedido na proporção de **30 (trinta) dias** ao empregado que conte com até 1 (um) ano de serviço para o mesmo empregador. Este é o prazo inicial para o aviso prévio proporcional ao tempo de serviço.
*   **Art. 487, inciso II**: Prevê um prazo de **trinta dias** para os empregados que percebem salário por quinzena ou mês, ou que tenham mais de doze meses de serviço na empresa.

Embora o Art. 487, inciso I, mencione um prazo de **oito dias** para pagamentos efetuados por semana ou tempo inferior, este mesmo inciso faz uma remissão ao Art. 7º, XXI, da Constituição Federal de 1988. Considerando as disposições que estabelecem um prazo de 30 dias para as situações de menor tempo de serviço (Art. 23, § 1º) e para a maioria dos casos de pagamento (Art. 487, II), o prazo mínimo a ser observado é de **30 (trinta) dias**.

Além disso, o Art. 23, § 2º, indica que ao aviso prévio de 30 dias serão acrescidos **3 (três) dias por ano de serviço** prestado para o mesmo empregador, até o máximo de **60 (sessenta) dias** adicionais, perfazendo um total de até **90 (noventa) dias**.

======================================================================
✅ Pergunta #3 — JORNADA DE TRABALHO

P: Qual é a jornada máxima de trabalho diária e semanal prevista na CLT?

[ESPERADO]
A jornada máxima é de 8 horas diárias e 44 horas semanais, conforme o Art. 58 da CLT. Acordos ou convenções coletivas podem prever compensações de jornada e bancos de horas.

[GERADO]
Com base exclusivamente nos tre trechos da CLT fornecidos, a jornada máxima de trabalho diária e semanal varia conforme a categoria do empregado:

**Jornada Diária Máxima:**

*   **Empregados em qualquer atividade privada (regra geral):**
    *   Conforme o Art. 58, a duração normal do trabalho não excederá **8 (oito) horas diárias**.
    *   Com o acréscimo de horas extras, conforme o Art. 59, a duração diária poderá ser acrescida em até **2 (duas) horas**, totalizando um máximo de **10 (dez) horas diárias**.

*   **Aprendizes:**
    *   Conforme o Art. 432, a duração do trabalho do aprendiz não excederá **6 (seis) horas diárias**.
    *   No entanto, o § 1º do Art. 432 permite que o limite seja de até **8 (oito) horas diárias** para aprendizes que já tiverem completado o ensino fundamental, desde que essas horas incluam a aprendizagem teórica.

*   **Empregados Domésticos:**
    *   Conforme o Art. 2º, a duração normal do trabalho doméstico não excederá **8 (oito) horas diárias**.

*   **Empregados em Minas no Subsolo:**
    *   Conforme o Art. 293, a duração normal do trabalho efetivo não excederá **6 (seis) horas diárias**.

*   **Motoristas Profissionais:**
    *   Conforme o Art. 235-C, a jornada diária de trabalho será de **8 (oito) horas**.
    *   Admite-se a prorrogação por até **2 (duas) horas extraordinárias**, totalizando **10 (dez) horas diárias**.
    *   Mediante previsão em convenção ou acordo coletivo, a prorrogação pode ser por até **4 (quatro) horas extraordinárias**, totalizando **12 (doze) horas diárias**.

**Jornada Semanal Máxima:**

*   **Empregados Domésticos:**
    *   Conforme o Art. 2º, a duração normal do trabalho doméstico não excederá **44 (quarenta e quatro) horas semanais**.

*   **Empregados em Minas no Subsolo:**
    *   Conforme o Art. 293, a duração normal do trabalho efetivo não excederá **36 (trinta e seis) horas semanais**.

*   **Para as demais categorias (empregados em atividade privada em geral, aprendizes e motoristas profissionais):**
    *   Não encontrei essa informação nos trechos da CLT disponíveis, que especificam apenas os limites diários ou mencionam a soma das jornadas semanais sem definir um limite numérico para a jornada semanal em si.

======================================================================
✅ Pergunta #4 — HORA EXTRA

P: Qual o acréscimo mínimo que deve ser pago ao trabalhador por hora extra?

[ESPERADO]
O acréscimo mínimo é de 50% sobre o valor da hora normal, conforme o Art. 59 da CLT. Convenções coletivas podem prever percentuais maiores. O limite de horas extras é de 2 horas por dia.

[GERADO]
Conforme o Art. 59, § 1º da CLT, a remuneração da hora extra será, pelo menos, **50% (cinquenta por cento)** superior à da hora normal.

======================================================================
✅ Pergunta #5 — FGTS

P: Qual é o percentual do FGTS que o empregador deve depositar mensalmente?

[ESPERADO]
O empregador deve depositar mensalmente o equivalente a 8% da remuneração paga ao empregado na conta vinculada do FGTS. Na hipótese de demissão sem justa causa, o empregador paga adicionalmente uma multa de 40% sobre o saldo do fundo.

[GERADO]
Conforme o Art. 34, inciso IV, da CLT, o recolhimento para o FGTS (Fundo de Garantia do Tempo de Serviço) é de **8% (oito por cento)**. Este valor é parte do Simples Doméstico e é a cargo do empregador doméstico.

======================================================================
✅ Pergunta #6 — LICENÇA MATERNIDADE

P: Qual é a duração da licença-maternidade prevista na CLT?

[ESPERADO]
A licença-maternidade tem duração de 120 dias, conforme o Art. 392 da CLT. Durante esse período, a empregada não pode ser dispensada sem justa causa, desde a confirmação da gravidez até 5 meses após o parto.

[GERADO]
Conforme os trechos da CLT fornecidos, a duração da licença-maternidade é de **120 (cento e vinte) dias**.

Essa duração é estabelecida para:
*   A empregada gestante (Art. 392, caput).
*   A empregada doméstica gestante (Art. 25, caput da Lei Complementar nº 150/2015, que remete à CLT).
*   A empregada que adotar ou obtiver guarda judicial para fins de adoção de criança ou adolescente (Art. 392-A, que remete ao Art. 392).

Mesmo em caso de parto antecipado, a mulher terá direito aos **120 (cento e vinte) dias** de licença-maternidade (Art. 392, § 3º).

======================================================================
✅ Pergunta #7 — INTERVALO INTRAJORNADA

P: Qual é o intervalo mínimo para refeição e descanso em jornadas acima de 6 horas?

[ESPERADO]
Para jornadas superiores a 6 horas, o intervalo mínimo é de 1 hora, conforme o Art. 71 da CLT. Para jornadas entre 4 e 6 horas, o intervalo é de 15 minutos. O intervalo não pode ser suprimido ou reduzido, salvo por convenção coletiva.

[GERADO]
Conforme o Art. 71 da CLT, em qualquer trabalho contínuo que exceda 6 (seis) horas, é obrigatória a concessão de um intervalo para repouso ou alimentação. Este intervalo será, no mínimo, de **1 (uma) hora** e, salvo acordo escrito ou contrato coletivo em contrário, não poderá exceder de **2 (duas) horas**.

O Art. 383 da CLT reitera essa regra para a empregada (mulher), estabelecendo que o período para refeição e repouso não será inferior a **1 (uma) hora** nem superior a **2 (duas) horas**, salvo a hipótese prevista no Art. 71, § 3º.

É importante notar que, conforme o Art. 71, § 2º, os intervalos de descanso não são computados na duração do trabalho.

======================================================================
✅ Pergunta #8 — RESCISÃO

P: Quais verbas rescisórias o trabalhador recebe ao ser demitido sem justa causa?

[ESPERADO]
Na demissão sem justa causa, o trabalhador tem direito a: saldo de salário, aviso prévio (trabalhado ou indenizado), férias vencidas e proporcionais acrescidas de 1/3, 13º salário proporcional, e saque do FGTS com multa de 40% sobre o saldo. Conforme Arts. 477 e 487 da CLT.

[GERADO]
Com base exclusivamente nos trechos da CLT fornecidos, as verbas rescisórias que o trabalhador recebe ao ser demitido sem justa causa são as seguintes:

1.  **Indenização em Contratos por Prazo Determinado:**
    *   Conforme o **Art. 6º** da CLT, durante a vigência de contratos específicos (previstos nos incisos I e II do art. 4º), o empregador que despedir o empregado sem justa causa é obrigado a pagar-lhe, a título de indenização, **metade da remuneração** a que o empregado teria direito até o término do contrato.
    *   De forma similar, o **Art. 479** da CLT estabelece que, nos contratos que tenham um prazo estipulado (contratos por prazo determinado), o empregador que, sem justa causa, despedir o empregado, será obrigado a pagar-lhe, a título de indenização, e por **metade**, a remuneração a que teria direito até o término do contrato.
    *   O Parágrafo único do **Art. 479** esclarece que, para o cálculo dessa indenização, a parte variável ou incerta dos salários será feita de acordo com o prescrito para o cálculo da indenização referente à rescisão dos contratos por prazo indeterminado.
    *   *Explicação de termos:* "Remuneração" é o conjunto de todas as parcelas pagas ao empregado em decorrência do trabalho, incluindo o salário e outras vantagens. "Termo do contrato" refere-se à data final de um contrato com prazo pré-estabelecido.

2.  **Verbas Relativas a Férias:**
    *   **Férias Vencidas:** Conforme o **Art. 146** da CLT, na cessação do contrato de trabalho, qualquer que seja a sua causa, será devida ao empregado a remuneração simples ou em dobro, conforme o caso, correspondente ao período de férias cujo direito ele já tenha adquirido (ou seja, férias que ele já tinha direito a tirar, mas não tirou).
    *   **Férias Proporcionais (Período Incompleto):**
        *   Conforme o **Art. 147** da CLT, o empregado que for despedido sem justa causa, ou cujo contrato de trabalho se extinguir em prazo predeterminado, antes de completar **12 (doze) meses de serviço**, terá direito à remuneração relativa ao período incompleto de férias.
        *   Conforme o **Art. 146, Parágrafo único**, na cessação do contrato de trabalho após **12 (doze) meses de serviço**, o empregado, desde que não tenha sido demitido por justa causa, terá direito à remuneração relativa ao período incompleto de férias, na proporção de **1/12 (um doze avos)** por mês de serviço ou fração superior a **14 (quatorze) dias**.
        *   *Explicação de termos:* "Período incompleto de férias" refere-se às férias proporcionais, ou seja, o direito a férias que o empregado acumulou, mas ainda não completou o período aquisitivo (12 meses de trabalho) para ter direito às férias integrais.

3.  **Procedimentos Gerais na Extinção do Contrato:**
    *   O **Art. 477** da CLT estabelece que, na extinção do contrato de trabalho, o empregador deverá proceder à anotação na Carteira de Trabalho e Previdência Social, comunicar a dispensa aos órgãos competentes e realizar o pagamento das verbas rescisórias no prazo e na forma estabelecidos neste artigo.
    *   O § 2º do **Art. 477** determina que o instrumento de rescisão ou recibo de quitação deve ter especificada a natureza de cada parcela paga ao empregado e discriminado o seu valor.

**Informação não encontrada nos trechos da CLT disponíveis:**
Os trechos fornecidos não contêm informações sobre outras verbas rescisórias comuns em demissões sem justa causa para contratos por prazo indeterminado, como o aviso prévio, a multa de 40% sobre o Fundo de Garantia por Tempo de Serviço (FGTS) ou o direito ao seguro-desemprego.

======================================================================
✅ Pergunta #9 — SALÁRIO MÍNIMO

P: Como a CLT define o salário mínimo e quais necessidades ele deve cobrir?

[ESPERADO]
Conforme o Art. 76 da CLT, o salário mínimo é a contraprestação mínima devida ao trabalhador, fixada em lei, capaz de satisfazer as necessidades normais de alimentação, habitação, vestuário, higiene e transporte. Nenhum salário pode ser inferior ao mínimo vigente.

[GERADO]
Conforme os trechos da CLT fornecidos, o salário mínimo é definido da seguinte forma e deve cobrir as seguintes necessidades:

**Definição de Salário Mínimo:**

*   **Art. 76:** É a contraprestação mínima (o pagamento mínimo) devida e paga diretamente pelo empregador a todo trabalhador, incluindo o trabalhador rural, sem distinção de sexo, por dia normal de serviço.
*   **Art. 7º, IV:** É um direito dos trabalhadores urbanos e rurais, fixado em lei, nacionalmente unificado.

**Necessidades que o Salário Mínimo deve cobrir:**

Os trechos da CLT apresentam duas listas de necessidades que o salário mínimo deve ser capaz de satisfazer:

1.  **Conforme o Art. 76 e Art. 81:** O salário mínimo deve ser capaz de satisfazer as necessidades normais de:
    *   Alimentação
    *   Habitação (moradia)
    *   Vestuário (roupas)
    *   Higiene
    *   Transporte

    O **Art. 81** detalha que o salário mínimo (Sm) é determinado por uma fórmula que considera o valor das despesas diárias com esses itens.

2.  **Conforme o Art. 7º, IV (para o salário mínimo nacionalmente unificado):** Deve ser capaz de atender às necessidades vitais básicas do trabalhador e de sua família, incluindo:
    *   Moradia
    *   Alimentação
    *   Educação
    *   Saúde
    *   Lazer
    *   Vestuário
    *   Higiene
    *   Transporte
    *   Previdência social

    Este artigo também estabelece que o salário mínimo deve ter reajustes periódicos para preservar seu poder aquisitivo e veda sua vinculação para qualquer fim.

======================================================================
✅ Pergunta #10 — TRABALHO NOTURNO

P: Qual é o adicional noturno previsto na CLT e como é contada a hora noturna?

[ESPERADO]
O trabalho noturno, realizado entre 22h e 5h, confere ao trabalhador um adicional de 20% sobre a hora diurna, conforme o Art. 73 da CLT. A hora noturna é computada como 52 minutos e 30 segundos, o que gera mais horas efetivas dentro do mesmo turno.

[GERADO]
Com base nos trechos da CLT fornecidos, o adicional noturno e a contagem da hora noturna são definidos da seguinte forma:

**Adicional Noturno:**

*   **Regra Geral:** A remuneração do trabalho noturno deve ter um acréscimo de, no mínimo, **20% (vinte por cento)** sobre o valor da hora diurna. Isso é estabelecido no Art. 14, § 2º, e reiterado no Art. 73, caput. Para o trabalho noturno das mulheres, o acréscimo é de, no mínimo, **20% (vinte por cento)**, conforme o Art. 381, § 1º.
*   **Contratação Exclusiva para Trabalho Noturno:** Se o empregado for contratado exclusivamente para desempenhar trabalho noturno, o acréscimo de 20% será calculado sobre o salário anotado na Carteira de Trabalho e Previdência Social, conforme o Art. 14, § 3º.
*   **Casos Específicos:**
    *   **Atividades na Lavoura e Pecuária:** Para o trabalho noturno na lavoura (entre 21h de um dia e 5h do dia seguinte) e na pecuária (entre 20h de um dia e 4h do dia seguinte), o acréscimo é de **25% (vinte e cinco por cento)** sobre a remuneração normal, conforme o Art. 7º e seu Parágrafo único.
    *   **Operadores Cinematográficos:** Para operadores cinematográficos e seus ajudantes que executam trabalho em sessões diurnas extraordinárias e cumulativamente nas noturnas, o acréscimo é de **25% (vinte e cinco por cento)** sobre o salário da hora normal, conforme o Art. 235.

**Contagem da Hora Noturna:**

*   A hora de trabalho noturno terá duração de **52 (cinquenta e dois) minutos e 30 (trinta) segundos**. Esta regra é explicitada no Art. 14, § 1º, no Art. 73, § 1º, e também se aplica ao trabalho noturno das mulheres, conforme o Art. 381, § 2º.

**Período Considerado Noturno (Regra Geral):**

*   Para os efeitos da CLT, considera-se trabalho noturno aquele executado entre as **22 (vinte e duas) horas de um dia e as 5 (cinco) horas do dia seguinte**, conforme o Art. 14 e o Art. 73, § 2º.
*   Nos horários mistos, que abrangem períodos diurnos e noturnos, as regras do trabalho noturno (incluindo o adicional e a duração da hora) aplicam-se às horas de trabalho noturno, conforme o Art. 14, § 4º.

## 6. Análise Qualitativa

Preencha esta seção após executar as células acima, analisando os resultados obtidos.

### 6.1 Pontos Fortes Observados

- *(ex.: o modelo citou corretamente o número do artigo na maioria das perguntas)*
- *(ex.: linguagem clara e acessível, sem jargão excessivo)*
- *(ex.: respostas sobre jornada e hora extra foram precisas e completas)*

### 6.2 Pontos de Melhoria

- *(ex.: perguntas sobre FGTS geraram respostas genéricas sem o percentual correto)*
- *(ex.: o modelo às vezes cita informações que não estão nos trechos recuperados)*
- *(ex.: respostas muito longas para perguntas diretas)*

### 6.3 Casos de Falha

| # | Pergunta | Motivo do Erro |
|---|----------|----------------|
| - | -        | -              |

### 6.4 Hipóteses para os Erros

- **Chunking insuficiente:** o trecho relevante não foi recuperado pelo retriever (k muito baixo ou embedding fraco)
- **Prompt insuficiente:** o modelo não foi guiado a citar o artigo explicitamente
- **Ambiguidade da pergunta:** a pergunta pode ser interpretada de múltiplas formas

### 6.5 Próximos Passos

- [ ] Aumentar `k` no retriever para perguntas com baixa keyword accuracy
- [ ] Avaliar embeddings alternativos (ex.: `text-embedding-004` vs `text-embedding-3-small`)
- [ ] Implementar avaliação semântica com `sentence-transformers` (BLEU, ROUGE ou cosine similarity)
- [ ] Adicionar mais perguntas ao benchmark, incluindo casos-limite e perguntas ambíguas

---

### 6.6 Resultado Final

| Métrica               | Valor |
|-----------------------|-------|
| Keyword Accuracy      | ?/10  |
| Perguntas com artigo  | ?/10  |
| Perguntas completas   | ?/10  |
| Nota qualitativa geral| ? / 5 |

## 7. Avaliação de Relevância dos Chunks

Para cada pergunta, avaliamos se os chunks recuperados pelo retriever são de fato relevantes, usando duas métricas complementares:

| Métrica | Descrição | Vantagem | Limitação |
|---------|-----------|----------|-----------|
| **Cosine similarity** | Distância geométrica entre os embeddings da query e do chunk | Rápido, sem custo de tokens extra | Captura similaridade léxico-semântica, pode trazer falsos positivos |
| **LLM-as-judge** | Gemini avalia o chunk com nota 0–3 | Semântico, entende contexto jurídico | Custa tokens extras (1 chamada por chunk) |
| **Combined** | `0.4 × cosine + 0.6 × llm_score` | Balanceia velocidade e precisão | — |

> **Nota sobre tokens**: a célula abaixo avalia apenas as 3 primeiras perguntas do benchmark (18 chamadas ao Gemini) para economizar cota da API. Remova o `[:3]` para rodar todas as 10.

### 7.1 Scores de relevância por chunk (3 primeiras perguntas)

In [8]:
import pandas as pd
from src.retrieval.retriever import get_retriever
from src.retrieval.relevance import evaluate_chunks

retriever = get_retriever(k=6)

# Avalia relevância dos chunks para as 3 primeiras perguntas (economiza tokens)
relevance_results = []

for item in benchmark[:3]:
    docs = retriever.invoke(item["question"])
    scored = evaluate_chunks(item["question"], docs)

    for rank, s in enumerate(scored, start=1):
        relevance_results.append({
            "pergunta_id": item["id"],
            "topic": item["topic"],
            "rank": rank,
            "artigo": s["doc"].metadata.get("artigo", "—"),
            "cosine": s["cosine"],
            "llm_score": s["llm_score"],
            "combined": s["combined"],
            "trecho": s["doc"].page_content[:80] + "...",
        })

df_rel = pd.DataFrame(relevance_results)
pd.set_option("display.max_colwidth", 85)
df_rel

,pergunta_id,topic,rank,artigo,cosine,llm_score,combined,trecho
0,1,férias,1,Art. 130,0.692,0.0,0.277,Art. 130. Após cada período de 12 (doze) meses de vigência do contrato de trabal...
1,1,férias,2,Art. 140,0.649,0.0,0.259,"Art. 140. Os empregados contratados há menos de 12 (doze) meses gozarão, na opor..."
2,1,férias,3,Art. 146,0.635,0.0,0.254,"Art. 146. Na cessação do contrato de trabalho, qualquer que seja a sua causa, se..."
3,1,férias,4,Art. 17,0.633,0.0,0.253,Art. 17. O empregado doméstico terá direito a férias anuais remuneradas de 30 (t...
4,1,férias,5,Art. 134,0.630,0.0,0.252,"Art. 134. As férias serão concedidas por ato do empregador, em um só período, no..."
5,1,férias,6,Art. 129,0.625,0.0,0.250,Art. 129. Todo empregado terá direito anualmente ao gozo de um período de férias...
6,2,aviso prévio,1,Art. 487,0.714,0.0,0.285,"Art. 487. Não havendo prazo estipulado, a parte que, sem justo motivo, quiser re..."
7,2,aviso prévio,2,Art. 23,0.688,0.0,0.275,"Art. 23. Não havendo prazo estipulado no contrato, a parte que, sem justo motivo..."
8,2,aviso prévio,3,Art. 490,0.661,0.0,0.264,"Art. 490. O empregador que, durante o prazo do aviso prévio dado ao empregado, p..."
9,2,aviso prévio,4,Art. 491,0.654,0.0,0.261,"Art. 491. O empregado que, durante o prazo do aviso prévio, cometer qualquer das..."
10,2,aviso prévio,5,Art. 487,0.642,0.0,0.257,"empregado pré-avisado da despedida, mesmo que tenha recebido antecipadamente os ..."
11,2,aviso prévio,6,Art. 486,0.622,0.0,0.249,CONSOLIDAÇÃO DAS LEIS DO TRABALHO\n \n94\nCAPÍTULO VI – DO AVISO PRÉVIO\n(Vide Le...
12,3,jornada de trabalho,1,Art. 58,0.675,0.0,0.270,"Art. 58. A duração normal do trabalho, para os empregados em qualquer atividade ..."
13,3,jornada de trabalho,2,Art. 432,0.638,0.0,0.255,"Art. 432. A duração do trabalho do aprendiz não excederá de seis horas diárias, ..."
14,3,jornada de trabalho,3,Art. 2º,0.638,0.0,0.255,Art. 2º A duração normal do trabalho doméstico não excederá 8 (oito) horas diári...
15,3,jornada de trabalho,4,Art. 293,0.635,0.0,0.254,Art. 293. A duração normal do trabalho efetivo para os empregados em minas no su...
16,3,jornada de trabalho,5,Art. 235-C,0.634,0.0,0.254,Art. 235-C. A jornada diária de trabalho do motorista profissional será de 8 (o...
17,3,jornada de trabalho,6,Art. 59,0.627,0.0,0.251,"Art. 59. A duração diária do trabalho poderá ser acrescida de horas extras, em n..."

## 8. Avaliação de Recall

**Recall@k** mede se o artigo esperado para cada pergunta está entre os k chunks recuperados pelo retriever.

- **Hit**: o artigo esperado (ex: `Art. 130`) aparece no metadata de pelo menos um dos k chunks retornados
- **Miss**: o artigo esperado não foi recuperado — o pipeline nunca terá a informação correta, independente do LLM

Esta é a métrica mais crítica do RAG: um LLM perfeito não consegue responder corretamente se o retriever não trouxe o chunk certo.

In [9]:
import pandas as pd
from src.retrieval.retriever import get_retriever
from src.retrieval.relevance import score_cosine, score_llm

retriever = get_retriever(k=6)

# Avalia recall para todas as perguntas do benchmark
recall_results = []

for item in benchmark:
    docs = retriever.invoke(item["question"])
    retrieved_articles = [d.metadata.get("artigo", "") for d in docs]

    # Extrai artigos esperados das keywords (ex: "Art. 130")
    expected_arts = [kw for kw in item["expected_keywords"] if kw.startswith("Art.")]
    hit = any(art in retrieved_articles for art in expected_arts) if expected_arts else None

    recall_results.append({
        "id": item["id"],
        "topic": item["topic"],
        "expected_articles": ", ".join(expected_arts) if expected_arts else "—",
        "retrieved_articles": ", ".join(retrieved_articles[:4]) + ("..." if len(retrieved_articles) > 4 else ""),
        "recall_hit": "✅" if hit else ("❌" if hit is False else "N/A"),
    })

df_recall = pd.DataFrame(recall_results).set_index("id")
pd.set_option("display.max_colwidth", 60)

total_with_art = sum(1 for r in recall_results if r["recall_hit"] != "N/A")
hits = sum(1 for r in recall_results if r["recall_hit"] == "✅")
print(f"Recall@6 (artigo esperado entre os 6 chunks recuperados): {hits}/{total_with_art} = {hits/total_with_art:.0%}\n")
df_recall

Recall@6 (artigo esperado entre os 6 chunks recuperados): 8/8 = 100%

,topic,expected_articles,retrieved_articles,recall_hit
id,,,,
1,férias,Art. 130,"Art. 130, Art. 140, Art. 146, Art. 17...",✅
2,aviso prévio,Art. 487,"Art. 487, Art. 23, Art. 490, Art. 491...",✅
3,jornada de trabalho,Art. 58,"Art. 58, Art. 432, Art. 2º, Art. 293...",✅
4,hora extra,Art. 59,"Art. 59, Art. 296, Art. 305, Art. 241...",✅
5,FGTS,—,"Art. 34, Art. 21, Art. 22, Art. 14-A...",N/A
6,licença maternidade,Art. 392,"Art. 392, Art. 25, Art. 392-A, Art. 392-B...",✅
7,intervalo intrajornada,Art. 71,"Art. 5º, Art. 71, Art. 66, Art. 244...",✅
8,rescisão,—,"Art. 6º, Art. 147, Art. 479, Art. 477...",N/A
9,salário mínimo,Art. 76,"Art. 76, Art. 81, Art. 7º, Art. 458...",✅
10,trabalho noturno,Art. 73,"Art. 14, Art. 73, Art. 7º, Art. 381...",✅

## 9. RAG Agêntico vs RAG Padrão

O RAG agêntico implementado em `src/retrieval/agent.py` estende o pipeline padrão com um **loop de avaliação e retry**:

| Etapa | RAG Padrão | RAG Agêntico |
|-------|-----------|--------------|
| Retrieval | k=6, uma vez | k=8, até 3 tentativas |
| Avaliação dos chunks | ✗ | ✅ cosine + LLM-as-judge |
| Reformulação da query | ✗ | ✅ se relevância média < 0.45 |
| Filtragem de chunks irrelevantes | ✗ | ✅ apenas chunks acima do threshold |
| Custo por pergunta (tokens) | ~800 | ~3.000–8.000 (depende das tentativas) |

**Quando o agente reformula a query?**
Se a média dos scores combinados (`0.4 × cosine + 0.6 × llm_judge`) for abaixo de `0.45`, o agente pede ao Gemini para reescrever a query com termos mais específicos da CLT, e repete o retrieval.

**Quando vale o custo extra?**
- Perguntas ambíguas ou com vocabulário informal ("meu chefe me mandou embora, o que recebo?")
- Perguntas que cruzam múltiplos artigos
- Casos onde o RAG padrão retornou resposta vaga ("não encontrei na CLT")

### 9.1 Exemplo de execução

In [10]:
# Exemplo de uso do RAG agêntico
# (execute após as seções 7 e 8 para comparação)
from src.retrieval.agent import get_agent_answer

sample_question = benchmark[0]["question"]
print(f"Pergunta: {sample_question}\n")
print("Executando RAG agêntico (pode demorar — faz múltiplas chamadas)...")

agent_answer = get_agent_answer(sample_question, chat_history=[])
print(f"\nResposta agêntica:\n{agent_answer}")

c:\Users\teodo\OneDrive\Documentos\Faculdade\6 Semestre Data Science\NLP\clt-rag-chatbot\.venv\Lib\site-packages\langgraph\cache\base\__init__.py:8: LangChainPendingDeprecationWarning: The default value of `allowed_objects` will change in a future version. Pass an explicit value (e.g., allowed_objects='messages' or allowed_objects='core') to suppress this warning.
  from langgraph.checkpoint.serde.jsonplus import JsonPlusSerializer

Pergunta: Quantos dias de férias o trabalhador tem direito após 12 meses de trabalho?

Executando RAG agêntico (pode demorar — faz múltiplas chamadas)...

Resposta agêntica:
Conforme o Art. 130 da CLT, após cada período de 12 (doze) meses de vigência do contrato de trabalho, o empregado terá direito a férias na seguinte proporção, que varia de acordo com o número de faltas ao serviço:

*   **30 (trinta) dias corridos**, se não houver faltado ao serviço mais de 5 (cinco) vezes.
*   **24 (vinte e quatro) dias corridos**, se houver tido de 6 (seis) a 14 (quatorze) faltas.
*   **18 (dezoito) dias corridos**, se houver tido de 15 (quinze) a 23 (vinte e três) faltas.
*   **12 (doze) dias corridos**, se houver tido de 24 (vinte e quatro) a 32 (trinta e duas) faltas.

É importante notar que, conforme o § 1º do Art. 130, é vedado descontar as faltas do empregado ao serviço do período de férias.